#!/bin/bash

# Read the input TSV file and extract the host or IP addresses
awk -F'\t' 'NR > 1 { hosts[$1]++ } END { for (host in hosts) print host, hosts[host] }' "$1" \
  | sort -k2,2nr -k1,1 | head -n11 | awk '{ print $1 }'
