#!/bin/bash

# List files in the current directory in long format
echo "Current Directory:"
ls -la

# Move up one directory (parent directory) and list its files in long format
echo -e "\nParent Directory:"
cd ..
ls -la

# Move to the /boot directory and list its files in long format
echo -e "\n/boot Directory:"
cd /boot
ls -la
#!/bin/bash
ls -la .. /boot
